CREATE DATABASE PORTFOLIO;

USE PORTFOLIO;

SHOW TABLES;

RENAME TABLE `final_dataset-checkpoint` TO final_dataset;

SELECT * FROM FINAL_DATASET LIMIT 5;

-- 1. MONTHLY REVENUE TREND

SELECT date_format(ORDER_PURCHASE_TIMESTAMP,'%Y-%M') AS MONTH,
SUM(TOTAL_PRICE) AS REVENUE,
COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM FINAL_DATASET
GROUP BY MONTH
ORDER BY MONTH;

-- 2) Revenue by State

SELECT CUSTOMER_STATE,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
SUM(TOTAL_PRICE) AS REVENUE
FROM FINAL_DATASET
GROUP BY CUSTOMER_STATE
ORDER BY REVENUE DESC;

-- 3) TOP PRODUCTS BY REVENUE

SELECT PRODUCT_ID,
SUM(TOTAL_PRICE) AS REVENUE,
COUNT(DISTINCT ORDER_ID)
FROM FINAL_DATASET
GROUP BY PRODUCT_ID
ORDER BY REVENUE DESC
LIMIT 10;

-- 4) Customer Type (New vs Repeat)
SELECT CASE 
WHEN
ORDERS = 1 THEN 'NEW'
ELSE 'REPEAT'
END AS CUSTOMER_TYPE,
COUNT(*) AS CUSTOMERS
FROM (
SELECT CUSTOMER_UNIQUE_ID,
COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM FINAL_DATASET
GROUP BY CUSTOMER_UNIQUE_ID
) T GROUP BY CUSTOMER_TYPE;

-- 5) Delivery Performance
SELECT CASE
WHEN ORDER_DELIVERED_CUSTOMER_DATE <= ORDER_ESTIMATED_DELIVERY_DATE
THEN 'ON TIME'
ELSE 'LATE'
END AS DELIVERY_STATUS,
COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM FINAL_DATASET
WHERE ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY DELIVERY_STATUS;

-- 6) Average Delivery Time

SELECT AVG(datediff(ORDER_DELIVERED_CUSTOMER_DATE,ORDER_PURCHASE_TIMESTAMP)) AS AVERAGE_DELIVERY_DAYS
FROM FINAL_DATASET
WHERE ORDER_DELIVERED_CUSTOMER_DATE;

-- 7) Top Cities
SELECT CUSTOMER_CITY,
SUM(TOTAL_PRICE) AS REVENUE
FROM FINAL_DATASET
GROUP BY CUSTOMER_CITY
ORDER BY REVENUE DESC
LIMIT 10;
	
